import clsx from 'clsx';
import type { Metadata } from 'next';
import './globals.css';
import localFont from 'next/font/local';

export const sfProText = localFont({
  src: [
    { path: '../../public/fonts/SFPro/SF-Pro-Text-Regular.otf', weight: '400' },
    { path: '../../public/fonts/SFPro/SF-Pro-Text-Medium.otf', weight: '500' },
    {
      path: '../../public/fonts/SFPro/SF-Pro-Text-Semibold.otf',
      weight: '600',
    },
    { path: '../../public/fonts/SFPro/SF-Pro-Text-Bold.otf', weight: '700' },
  ],
  variable: '--font-sf-text',
});

export const metadata: Metadata = {
  title: 'Social Media App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={clsx(sfProText.variable, 'antialiased')}>
        {children}
      </body>
    </html>
  );
}
